# Generated by Django 4.1.1 on 2024-10-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChucVuNhanVien',
            fields=[
                ('ma_chuc_vu_nv', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ten_chuc_vu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenNganh',
            fields=[
                ('ma_chuyen_nganh', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ten_chuyen_nganh', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('ma_hop_dong', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('loai_hop_dong', models.CharField(max_length=50)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('ghi_chu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nhan_vien', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mat_khau', models.CharField(max_length=100)),
                ('ho_ten', models.CharField(max_length=50)),
                ('ngay_sinh', models.DateField()),
                ('que_quan', models.CharField(max_length=100)),
                ('hinh_anh', models.TextField()),
                ('gioi_tinh', models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam')])),
                ('dan_toc', models.CharField(max_length=10)),
                ('sdt_nhan_vien', models.CharField(max_length=11)),
                ('trang_thai', models.BooleanField()),
                ('cmdn', models.CharField(max_length=50)),
                ('ma_chuc_vu_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.chucvunhanvien')),
                ('ma_chuyen_nganh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.chuyennganh')),
                ('ma_hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.hopdong')),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('ma_phong_ban', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ten_phong_ban', models.CharField(max_length=50)),
                ('dia_chi', models.CharField(max_length=50)),
                ('sdt_phong_ban', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TrinhDoHocVan',
            fields=[
                ('ma_trinh_do_hoc_van', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ten_trinh_do', models.TextField()),
                ('he_so_bac', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ThoiViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do', models.TextField()),
                ('ngay_thoi_viec', models.DateField()),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ma_phong_ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.phongban'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ma_trinh_do_hoc_van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.trinhdohocvan'),
        ),
        migrations.CreateModel(
            name='Luong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luong_toi_thieu', models.IntegerField()),
                ('he_so_luong', models.FloatField()),
                ('bhxh', models.FloatField()),
                ('bhyt', models.FloatField()),
                ('bhtn', models.FloatField()),
                ('phu_cap', models.FloatField()),
                ('thue_thu_nhap', models.FloatField()),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='LuanChuyenNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do_chuyen', models.TextField()),
                ('ma_phong_ban_chuyen', models.CharField(max_length=30)),
                ('ma_phong_ban_den', models.CharField(max_length=30)),
                ('ngay_chuyen', models.DateField()),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='KyLuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do', models.TextField()),
                ('tien_ky_luat', models.IntegerField()),
                ('thang_ky_luat', models.DateField()),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='KhenThuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang_thuong', models.DateField()),
                ('ly_do', models.TextField()),
                ('tien_thuong', models.IntegerField()),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietLuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_chi_tiet_bang_luong', models.CharField(max_length=30)),
                ('luong_co_ban', models.FloatField()),
                ('bhxh', models.FloatField()),
                ('bhyt', models.FloatField()),
                ('bhtn', models.FloatField()),
                ('ngay_nhan_luong', models.DateField()),
                ('tong_tien_luong', models.CharField(max_length=30)),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='CapNhatLuong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('luong_hien_tai', models.IntegerField()),
                ('luong_sau_cap_nhat', models.IntegerField()),
                ('bhxh', models.FloatField()),
                ('bhyt', models.FloatField()),
                ('bhtn', models.FloatField()),
                ('phu_cap', models.FloatField()),
                ('thue_thu_nhap', models.FloatField()),
                ('he_so_luong', models.FloatField()),
                ('ngay_cap_nhat', models.DateField()),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='CapNhatHocVan',
            fields=[
                ('ma_cap_nhat', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_cap_nhat', models.DateField()),
                ('ma_trinh_do_truoc', models.CharField(max_length=30)),
                ('ma_trinh_do_cap_nhat', models.CharField(max_length=30)),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
    ]
