# Generated by Django 4.1.1 on 2024-10-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='hinh_anh',
            field=models.ImageField(upload_to='hinh_anh_nhan_vien/'),
        ),
    ]
