# Generated by Django 4.1.1 on 2024-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_nhanvien_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='hinh_anh_nhan_vien/'),
        ),
    ]
