# Generated by Django 4.1.1 on 2024-10-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_nhanvien_hinh_anh'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietluong',
            name='phu_cap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chitietluong',
            name='bhtn',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chitietluong',
            name='bhxh',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chitietluong',
            name='bhyt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chitietluong',
            name='tong_tien_luong',
            field=models.FloatField(),
        ),
    ]
