# Generated by Django 5.1.2 on 2024-10-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_chitietluong_phu_cap_alter_chitietluong_bhtn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khenthuong',
            name='ma_nhan_vien',
        ),
        migrations.RemoveField(
            model_name='luanchuyennhanvien',
            name='ma_nhan_vien',
        ),
        migrations.DeleteModel(
            name='CapNhatHocVan',
        ),
        migrations.DeleteModel(
            name='KhenThuong',
        ),
        migrations.DeleteModel(
            name='LuanChuyenNhanVien',
        ),
    ]
