# Generated by Django 5.1.2 on 2024-10-29 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_khenthuong_ma_nhan_vien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luong',
            name='bhtn',
        ),
        migrations.RemoveField(
            model_name='luong',
            name='bhxh',
        ),
        migrations.RemoveField(
            model_name='luong',
            name='bhyt',
        ),
        migrations.RemoveField(
            model_name='luong',
            name='he_so_luong',
        ),
        migrations.RemoveField(
            model_name='luong',
            name='luong_toi_thieu',
        ),
        migrations.RemoveField(
            model_name='luong',
            name='phu_cap',
        ),
        migrations.RemoveField(
            model_name='luong',
            name='thue_thu_nhap',
        ),
        migrations.AddField(
            model_name='luong',
            name='bao_hiem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='luong',
            name='luong_thoa_thuan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='luong',
            name='luong_tong',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='luong',
            name='ngay_tra_luong',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='luong',
            name='so_gio_lam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='luong',
            name='tien_tang_ca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ChiTietLuong',
        ),
    ]
