# Generated by Django 5.1.2 on 2024-10-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_luong_bhtn_remove_luong_bhxh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luong',
            old_name='ma_nhan_vien',
            new_name='nhan_vien',
        ),
    ]
