# Generated by Django 5.1.2 on 2024-10-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_rename_ma_nhan_vien_luong_nhan_vien'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapNhatLuong',
        ),
    ]
