# Generated by Django 5.1.2 on 2024-10-29 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_delete_capnhatluong'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cham_cong', models.DateField(default=django.utils.timezone.now)),
                ('gio_vao', models.TimeField(blank=True, null=True)),
                ('gio_ra', models.TimeField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
    ]
