# Generated by Django 5.1.2 on 2024-10-29 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_chamcong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamcong',
            name='gio_ra',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='gio_vao',
            field=models.TimeField(blank=True, default=datetime.time(7, 0), null=True),
        ),
    ]
