# Generated by Django 5.1.2 on 2024-11-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_chamcong_gio_ra_alter_chamcong_gio_vao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luong',
            options={'verbose_name': 'Lương', 'verbose_name_plural': 'Lương'},
        ),
        migrations.RenameField(
            model_name='luong',
            old_name='luong_thoa_thuan',
            new_name='bao_hiem_that_nghiep',
        ),
        migrations.RemoveField(
            model_name='luong',
            name='bao_hiem',
        ),
        migrations.RemoveField(
            model_name='luong',
            name='luong_tong',
        ),
        migrations.AddField(
            model_name='luong',
            name='bao_hiem_xa_hoi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='luong',
            name='bao_hiem_y_te',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='luong',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luong',
            name='khau_tru',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='luong',
            name='luong_co_ban',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='luong',
            name='luong_thuc_nhan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='luong',
            name='phu_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='luong',
            name='thue_thu_nhap_ca_nhan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='luong',
            name='thuong',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='luong',
            name='so_gio_lam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='luong',
            name='tien_tang_ca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
