# Generated by Django 5.1.2 on 2024-12-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_luong_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luong',
            name='so_gio_lam',
        ),
        migrations.AddField(
            model_name='luong',
            name='hesoluong',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='KhenThuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang_thuong', models.DateField()),
                ('ly_do', models.TextField()),
                ('tien_thuong', models.IntegerField()),
                ('ma_nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.nhanvien')),
            ],
        ),
    ]
